export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_DONE = "LOGOUT_DONE";

export const SIGNUP_INIT = "SIGNUP_INIT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const VERIFICATION_INIT = "VERIFICATION_INIT";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILURE = "VERIFICATION_FAILURE";

export const RESEND_VERIFICATION_INIT = "RESEND_VERIFICATION_INIT";

export const FORGET_PASSWORD_SEND_CODE_INIT = "FORGET_PASSWORD_SEND_CODE_INIT";
export const FORGET_PASSWORD_SEND_CODE_SUCCESS = "FORGET_PASSWORD_SEND_CODE_SUCCESS";


export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";

export const GET_PHOTOGRAPHERS = "GET_PHOTOGRAPHERS";
export const GET_PHOTOGRAPHERS_SUCCESS = "GET_PHOTOGRAPHERS_SUCCESS";

export const SOCIAL_LOGIN_FACEBOOK_INIT = "SOCIAL_LOGIN_FACEBOOK_INIT";
